server:
  port: 8086
hm:
  swagger:
    title: 交易服务接口文档
    package: com.mall.pay.controller
  db:
    database: hm-pay
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
  sentinel:
    enabled: true # 开启Feign对Sentinel的整合