server:
  port: 8080
mall:
  jwt:
    location: classpath:mall.jks
    alias: mall
    password: mall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
