server:
  port: 8083
mall:
  jwt:
    location: classpath:mall.jks
    alias: mall
    password: 123456
    keyPassword: 123456
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /users/register
      - /items/**
      - /hi
      - /doc.html
      - /swagger-ui.html
      - /webjars/**
      - /swagger-resources
      - /swagger-resources/**
      - /mall/v2/api-docs
      - /mall/v2/api-docs-ext
      - /user/v2/api-docs
      - /user/v2/api-docs-ext
      - /item/v2/api-docs
      - /item/v2/api-docs-ext
      - /cart/v2/api-docs
      - /cart/v2/api-docs-ext
      - /trade/v2/api-docs
      - /trade/v2/api-docs-ext
      - /pay/v2/api-docs
      - /pay/v2/api-docs-ext

