server:
  port: 8082
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
  sentinel:
    enabled: true
mall:
  swagger:
    title: 购物车服务接口文档
    package: com.lonelyash.cart.controller
  db:
    database: mall-cart
  cart:
    maxAmount: 100
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true
